app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employee','EmployeeController');
Route::resource('department','DepartmentController');

Auth::routes();
Route::post('employee/create/fetch','EmployeeController@fetch')->name('dropdown.fetch');
Route::get('/home', 'HomeController@index')->name('home');

//Route::post('/province/fetch','DropdownController@fetch')->name('dropdown.fetch');

app/app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = "Employee";

    protected $fillable = ['id','emp_name','emp_surName','emp_img','emp_sex','emp_phone','emp_email','emp_birthday','emp_nationality',
    'emp_qualification','position_pos_id'];
}

app/app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // $emp = DB::table('Employee')->get();
        $employee = DB::table('Department')->join('Position','departm_dep_id','=','Department.id')->join('Employee','position_pos_id','=','Position.id')->orderBy('emp_name')->get();
        //dd($employee);
        return view('employee.index',compact('employee'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Department = DB::table('Department')->get();
        $Position = DB::table('Position')->get();
        //dd($Department);
        return view('employee.create',compact('Department','Position'));
    }
    public function fetch(Request $request)
    {
        $id= $request->get('select');
        $result = array();
        $query=DB::table('Department')
        ->join('Position','Department.id','=','Position.departm_dep_id')
        ->select('Position.id','Position.pos_name')
        ->where('Department.id',$id)
        ->groupBy('Position.id')
        ->get();
        $output ='<option value="">เลือกตำแหน่ง</option>';
        foreach($query as $row){
           
            $output.='<option value="'.$row->id.'"  >'.$row->pos_name.'</option>';
        }
        echo $output;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $request->validate(
        //     [
        //         'ACC_NO' => 'required|max:10',
        //         'ACC_NAME' => 'required|max:50',
        //         'ACC_Surname' => 'required|max:100',
        //         'Balance' => 'required'
        //     ]
        // );
        $employee = new Employee;
        $employee->emp_name = $request->get('emp_name');
        $employee->emp_surName = $request->get('emp_surName');
        $employee->emp_img = $request->get('emp_img');
        $employee->emp_sex = $request->get('emp_sex');
       
        $employee->emp_phone = $request->get('emp_phone');
        $employee->emp_email = $request->get('emp_email');
        $employee->emp_birthday = $request->get('emp_birthday');
        $employee->emp_nationality = $request->get('emp_nationality');
        $employee->emp_qualification = $request->get('emp_qualification');
        $employee->position_pos_id = $request->get('position_pos_id');
       
        $employee->save();

        return redirect('employee');
    }
    public function storeDep(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee=Employee::find($id);
        
        return view('employee.edit',compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employee = employee::find($id);
        // $request->validate(
        //     [
        //         'ACC_No' => 'required|max:10',
        //         'ACC_Name' => 'required|max:0',
        //         'ACC_Sername' => 'required|max:10',
        //         'ACC_Balance' => 'required'
        //     ]
        // );
        $employee->emp_name =  $request->emp_name;
        $employee->emp_surName = $request->emp_surName;    
        $employee->emp_sex = $request->emp_sex;
        $employee->emp_email = $request->emp_email;
        $employee->emp_phone = $request->emp_phone;
        $employee->emp_birthday = $request->emp_birthday;
        $employee->emp_nationality = $request->emp_nationality;
        $employee->emp_qualification = $request->emp_qualification;
        $employee->position_pos_id = $request->position_pos_id;
        $employee->update();
        return redirect("employee");
        // $employee=Employee::find($id);
        // $employee = new Employee;
        // $employee->emp_name = $request->get('emp_name');
        // $employee->emp_surName = $request->get('emp_surName');
        // $employee->emp_img = $request->get('emp_img');
        // $employee->emp_sex = $request->get('emp_sex');
       
        // $employee->emp_phone = $request->get('emp_phone');
        // $employee->emp_email = $request->get('emp_email');
        // $employee->emp_birthday = $request->get('emp_birthday');
        // $employee->emp_nationality = $request->get('emp_nationality');
        // $employee->emp_qualification = $request->get('emp_qualification');
        // $employee->position_pos_id = $request->get('position_pos_id');
       
        // $employee->save();

        // return redirect('employee');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee =Employee::find($id);
        $employee->delete();
        return redirect("employee");
    }
}

app/resources/views/employee/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Hello, world!</title>
    <style media="Screnn">
 
    </style>
  
  <body class="bg-light ">
        <nav class="navbar navbar-light " style="background-color: #FFFFFF;">
                <div class="container">
                        <a class="navbar-brand" href="http://localhost" >
                            Laravel
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <!-- Left Side Of Navbar -->
                            <ul class="navbar-nav mr-auto">
        
                            </ul>
        
                            <!-- Right Side Of Navbar -->
                            <ul class="navbar-nav ml-auto">
                                <!-- Authentication Links -->
                                                            <li class="nav-item">
                                        <a class="nav-link" href="http://localhost/login">Login</a>
                                    </li>
                                                                    <li class="nav-item">
                                            <a class="nav-link" href="http://localhost/register">Register</a>
                                        </li>
                                                                                </ul>
                        </div>
                    </div>
              </nav>
    <main class="py-4 bg-light">
    <div class="container box">
        <a  class="btn btn-success" href="{{ route('employee.index') }}">หน้าหลัก</a><br><br>

        <form method="post" action="{{ route('employee.store') }}">
                {{ csrf_field() }}
        
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="emp_name">name</label>
                        <input type="text" class="form-control" name="emp_name" placeholder="name">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="emp_surName">Lastname</label>
                        <input type="text" class="form-control" name="emp_surName" placeholder="Last name">
                    </div>
                    <div class="form-group col-md-6">
                            <label >sex</label>
                        <select class="form-control form-control-sm " name="emp_sex">
                                <option value="female" >female</option>
                                <option value="male" >male</option>
                        </select>
                        </div>
                </div>    
                {{-- <div class="form-group">
                        <label for="emp_sex">sex</label>
                        <input type="text" class="form-control"   name="emp_sex" splaceholder="Another input">
                </div> --}}
                {{-- <div class="form-row">
                <div class="form-group">
                        <label >sex</label>
                        <select class="form-control form-control-sm position" name="emp_sex">
                                <option value="female" >female</option>
                                <option value="male" >male</option>
                        </select>
                </div>       
                </div> --}}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="emp_email">Email</label>
                        <input type="email" class="form-control" name="emp_email"  placeholder="email@hotmail.com">
                    </div>
                    <div class="form-group col-md-6">
                            <label for="emp_phone">Phone</label>
                            <input type="text" class="form-control" name="emp_phone" placeholder="09222222222">
                    </div>        
                </div> 
                <div class="form-group">
                        <label for="emp_birthday">birthday</label>
                        
                          <input class="form-control" type="date" name="emp_birthday" id="example-date-input">
                </div>
                <div class="form-group">
                        <label for="emp_nationality">nationality</label>
                        <input type="text" class="form-control"   name="emp_nationality" splaceholder="Another input">
                </div>
                <div class="form-group">
                        <label for="emp_qualification">qualification</label>
                        <input type="text" class="form-control"   name="emp_qualification" splaceholder="Another input">
                </div>
                           
                <div class="form-row">
                        <div class="form-group col-md-6">
                                <label >Department</label>
    
                                <select id="province"class="form-control form-control-sm province">
                                    <option >เลือกแผนก</option>
                                @foreach($Department as $row)
                                 <option value="{{ $row->id }}" >{{ $row->dep_name }}</option>
                                 
                                @endforeach 
                                </select>
                        </div>
                        <div class="form-group col-md-6">
                                <label >Position</label>
                                <select class="form-control form-control-sm position" name="position_pos_id">
                                        <option >เลือกตำแหน่ง</option>
                                </select>
                        </div>        
                    </div> 
                    
                    <div>
                            <button type="submit" class="btn btn-default">เพิ่ม</button>                    
                        </div>
       


      </form>
      <form method="post" action="{{ route('department.store') }}">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="dep_name">department</label>
            <input type="text" class="form-control"   name="dep_name" splaceholder="Another input">
            <div>
                <button type="submit" class="btn btn-default">เพิ่มแผนก</button>                    
            </div>
    </div>
      </form>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {{-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> --}}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
                  
        $(".province").change(function(){
           if($(this).val()!=''){ 
            var select=$(this).val();
            var _token=$('input[name="token"]').val();
            $.ajax({
                
                headers: {
                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                  },
                url:"{{route('dropdown.fetch')}}",
                method:"POST",
                data:{select:select,_token:_token},
                success:function(result){
                    //เสร็จแล้วทำอะไรต่อ
                    $('.position').html(result);
                    console.log(result)
                }
            
            })
           }
        });
        </script>  
    <main>
</body>
</head>
</html>

app/resources/views/employee/createBU.blade.php
<html>
    <head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
    
    
                    <div class="panel-heading">
                    <form method="post" action="{{ route('employee.store') }}">
                            {{ csrf_field() }}
                        <form>
                        <!-- <div class="form-group">
                            <label for="emp_id">id</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" name="emp_id" placeholder="Example input">
                        </div> -->
                        <div class="form-group">
                        <label for="emp_name">Name</label>
                        <input type="text" class="form-control"   name="emp_name" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="emp_surName">Surname</label>
                        <input type="text" class="form-control"   name="emp_surName" splaceholder="Another input">
                        </div>
                        <div class="custom-file">
                         <input type="file" name="emp_img" class="custom-file-input" id="customFile">
                         <label class="custom-file-label" for="emp_img">Choose file</label>
                        </div>
                        <div class="form-group">
                        <label for="emp_sex">sex</label>
                        <input type="text" class="form-control"   name="emp_sex" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="emp_email">email</label>
                        <input type="text" class="form-control"   name="emp_email" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="emp_phone">phone</label>
                        <input type="text" class="form-control"   name="emp_phone" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="emp_birthday">birthday</label>
                        <input type="text" class="form-control"   name="emp_birthday" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="emp_nationality">nationality</label>
                        <input type="text" class="form-control"   name="emp_nationality" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="emp_qualification">qualification</label>
                        <input type="text" class="form-control"   name="emp_qualification" splaceholder="Another input">
                        </div>
                        <div class="form-group">
                        <label for="position_pos_id">id</label>
                        <input type="text" class="form-control"   name="position_pos_id" splaceholder="Another input">
                        </div>
                        <div class="dropdown">
                        <label >Department</label>
    
                        <select id="province"class="form-control form-control-sm province">
                            <option >เลือกแผนก</option>
                        @foreach($Department as $row)
                         <option value="{{ $row->id }}">{{ $row->dep_name }}</option>
                        @endforeach 
                        </select>
                      
                        <label >Position</label>
                        <select class="form-control form-control-sm position">
                                <option >เลือกตำแหน่ง</option>
                        
                     
                        </select>
                      
                    </form>
    
                        <div>
                            <button type="submit" class="btn btn-default">เพิ่ม</button>                    
                        </div>
                    
                    </form>
                    </div>
                   
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
    </body>
    <script type="text/javascript">
                            
                    $(".province").change(function(){
                       if($(this).val()!=''){ 
                        var select=$(this).val();
                        var _token=$('input[name="token"]').val();
                        $.ajax({
                            
                            headers: {
                              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                              },
                            url:"{{route('dropdown.fetch')}}",
                            method:"POST",
                            data:{select:select,_token:_token},
                            success:function(result){
                                //เสร็จแล้วทำอะไรต่อ
                                $('.Position').html(result);
                            }
                        
                        })
                       }
                    });
                    </script>  
    </head>
    </html>
    
    

app/resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
<html>
<head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">


                <div class="panel-heading">
                <form method="post" action="{{ route('employee.update',$employee->id) }}">
                  
                    <form>
                            {{ csrf_field() }}
                            @method('PUT')
                    <!-- <div class="form-group">
                        <label for="emp_id">id</label>
                        <input type="text" class="form-control" id="formGroupExampleInput" name="emp_id" placeholder="Example input">
                    </div> -->
                    <div class="form-group">
                    <label for="emp_name">Name</label>
                    <input type="text" class="form-control"   name="emp_name" splaceholder="Another input" value="{{ $employee->emp_name}}">
                    </div>
                    <div class="form-group">
                    <label for="emp_surName">Surname</label>
                    <input type="text" class="form-control"   name="emp_surName" splaceholder="Another input" value="{{ $employee->emp_surName}}">
                    </div>
                    <div class="custom-file">
                     <input type="file" name="emp_img" class="custom-file-input" id="customFile">
                     <label class="custom-file-label" for="emp_img">Choose file</label>
                    </div>
                    <div class="form-group">
                    <label for="emp_sex">sex</label>
                    <input type="text" class="form-control"   name="emp_sex" splaceholder="Another input" value="{{ $employee->emp_sex}}">
                    </div>
                    <div class="form-group">
                    <label for="emp_email">email</label>
                    <input type="text" class="form-control"   name="emp_email" splaceholder="Another input" value="{{ $employee->emp_email}}">
                    </div>
                    <div class="form-group">
                    <label for="emp_phone">phone</label>
                    <input type="text" class="form-control"   name="emp_phone" splaceholder="Another input" value="{{ $employee->emp_phone}}">
                    </div>
                    <div class="form-group">
                    <label for="emp_birthday">birthday</label>
                    <input type="text" class="form-control"   name="emp_birthday" splaceholder="Another input" value="{{ $employee->emp_birthday}}">
                    </div>
                    <div class="form-group">
                    <label for="emp_nationality">nationality</label>
                    <input type="text" class="form-control"   name="emp_nationality" splaceholder="Another input" value="{{ $employee->emp_nationality}}">
                    </div>
                    <div class="form-group">
                    <label for="emp_qualification">qualification</label>
                    <input type="text" class="form-control"   name="emp_qualification" splaceholder="Another input" value="{{ $employee->emp_qualification}}">
                    </div>
                    <div class="form-group">
                    <label for="position_pos_id">id</label>
                    <input type="text" class="form-control"   name="position_pos_id" splaceholder="Another input" value="{{ $employee->position_pos_id}}">
                    </div>
                    <div class="dropdown">
                  
                  
                </form>

                    <div>
                        <button type="submit" class="btn btn-default">เปิดบัญชี</button>                    
                    </div>
                
                </form>
                </div>
               
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
                $(".province").change(function(){
                    var select=$(this).val();
                    console.log("ll");
                });
                </script>  
</head>
</html>
@endsection

app/resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">

            </div>

            <div class="panel-body">
            <a  class="btn btn-success" href="{{ route('employee.create') }}">เพิ่ม</a>
            
            <table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">name</th>
      <th scope="col">surName</th>
      <th scope="col">img</th>
      <th scope="col">sex</th>
      <th scope="col">phone</th>
      <th scope="col">email</th>
      <th scope="col">birthday</th>
      <th scope="col">nationality</th>
      <th scope="col">qualification</th>
      
      <th scope="col">position</th>
      <th scope="col">department</th>
      <th scope="col" colspan=2>Option</th>
    </tr>
  </thead>
  <?php $i=1; ?>
  @foreach($employee as $row)
  <tbody>
    

      <th scope="col">{{ $row->id }}</th>
      <th scope="col">{{ $row->emp_name }}</th>
      <th scope="col">{{ $row->emp_surName }}</th>
      <th scope="col">{{ $row->emp_img }}</th>
      <th scope="col">{{ $row->emp_sex }}</th>
      <th scope="col">{{ $row->emp_phone }}</th>
      <th scope="col">{{ $row->emp_email }}</th>
      <th scope="col">{{ $row->emp_birthday }}</th>
      <th scope="col">{{ $row->emp_nationality }}</th>
      <th scope="col">{{ $row->emp_qualification }}</th>

      <th scope="col">{{ $row->pos_name }}</th>
      <th scope="col">{{ $row->dep_name }}</th>
      <th><a class="btn btn-warning" href="{{ route('employee.edit',$row->id) }}">edit</a></th>
      
      <th><form action="{{ route('employee.destroy',$row->id) }}" method ="post"> 
          @csrf 
          @method("DELETE")
          <button class="btn btn-danger">Delete</button>
        </form>
      </th>    
  </tbody>
 @endforeach 
</table>

            </div>
        </div>
    </div>
</div>
@endsection

app/resources/views/employee/update.blade.php
@extends('layouts.app')

@section('content')
<html>



<div class="container">
   <h1>hello</h1>
</div>


</html>
@endsection